#pragma once

/* Unedfine things here before redefining them in the keymap config
 * This way gcc stays happy and the keymap config stays clean of #undefs
 */

#undef RGB_MATRIX_KEYPRESSES
#undef DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef DISABLE_RGB_MATRIX_BAND_SAT
#undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef DISABLE_RGB_MATRIX_SPLASH
#undef DISABLE_RGB_MATRIX_MULTISPLASH
#undef DISABLE_RGB_MATRIX_SOLID_SPLASH
#undef DISABLE_RGB_MATRIX_SOLID_MULTISPLASH
#undef DISABLE_RGB_MATRIX_DIGITAL_RAIN
#undef RGB_MATRIX_STARTUP_MODE
#undef DEBOUNCE
